set_property PACKAGE_PIN T22 [get_ports LED]
set_property PACKAGE_PIN F22 [get_ports R]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN H17 [get_ports {sw[1]}]
set_property PACKAGE_PIN M15 [get_ports {sw[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports LED]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
